INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY)
VALUES ('Laptop', 'Business laptop for QA testing', 55000.00, 10, 'ELEC');

INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY)
VALUES ('Keyboard', 'Mechanical keyboard', 2500.00, 25, 'ELEC');

INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY)
VALUES ('Office Chair', 'Ergonomic office chair', 7500.00, 8, 'FURN');
